name: vidyen_app
description: VIDYEN Conference Management Mobile App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  http: ^1.2.1

  # Local storage (token)
  shared_preferences: ^2.2.3
  #flutter_secure_storage: ^9.0.0

  # State management
  provider: ^6.1.2

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
